apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-server
  name: nginx-server
  namespace: default
spec:
  containers:
  - image: nginx:1.19.4
    imagePullPolicy: Always
    name: nginx
    resources:
        limits:
            cpu: 100m
            memory: 256Mi
        requests: 
             cpu: 100m
             memory: 256Mi
   